#!/bin/bash

echo "So the parameters are $*"
echo "You have $# parameters"

for parameters in $*; do
    if [ -f $parameters ]
    then
        echo "Those $parameters are files"
    else
        echo "Those $parameters are not files"
    fi
    echo $parameters
done

timer="sleep 1"
$timer
echo "Now lets do some other loop "
for i in {1..3}; do
    echo -n "."
    $timer
done
printf "\n"
echo "It's called While Loop and it will be executed 
until the given condition doesn't reached"
$timer
echo "for example"

sum=0
while true; do
    read -p "enter your value, if you wanna stop input "quit" " value_1
    if [ "$value_1" == "quit" ]; then
    break
    fi

    sum=$(($sum+$value_1))
    echo "total value: $sum"
done