#!/bin/bash

echo "Lets read what you've got there"

read -p "What's the password: " user_pwd

echo "is that's your password: $user_pwd?"

read -p "Enter 'Yes' or 'No': " answer

if [ "$answer" = "Yes" ]
then 
    echo "He he boi, we got you"
else 
    echo "Oh man, we almost got you"
fi
