#!/bin/bash


echo "Let's make some function and boolean check"

function touch_file() {
    file_name=$1
    is_shell_script=$2
    touch $file_name
    echo "file $file_name created"

    if [ "$is_shell_script" = true ]; then
        chmod u+x $file_name
        echo "Added permissions"
    fi
}

touch_file testme.sh
touch_file testhim.exe
touch_file testall.doc true